_BASE_: "fullmodality_base.yaml"
DEBUG: True

CHECKPOINTS:
  SAVE: [10]
  INFERENCE: 10

LOGGING:
  STEP_FREQUENCY: 10
  STEP_MAX_SAMPLES: 100
  EPOCH_FREQUENCY: 1
  EPOCH_MAX_SAMPLES: 100

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 16
  EPOCHS: 10


DATALOADER:
  INPUT_MODE: 's1s2'  # 's1', 's2' or 's1s2'
  INCLUDE_INCOMPLETE: True

AUGMENTATION:
  CROP_SIZE: 16