_BASE_: "base.yaml"
DEBUG: False
GROUP: 'masked_mmtmdsunet_s1s2'

LOGGING:
  BATCH_SIZE: 1

MODEL:
  BATCH_SIZE: 2
  TYPE: 'mmtmdualstreamunet'
  DUAL_LOSS: True

DATALOADER:
  INPUT_MODE: 's1s2'
  INCLUDE_INCOMPLETE: True