_BASE_: "missingmodality_base.yaml"
DEBUG: False

CHECKPOINTS:
  SAVE: [50]
  INFERENCE: 50

LOGGING:
  STEP_FREQUENCY: 10
  STEP_MAX_SAMPLES: 100
  EPOCH_FREQUENCY: 5
  EPOCH_MAX_SAMPLES: 100

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 2
  EPOCHS: 50

MODEL:
  TYPE: 'reconstructionnet_v1'
  TOPOLOGY: [64, 128,]

RECONSTRUCTION_TRAINER:
  LOSS_TYPE: 'L2'
  ALPHA: 0.9

DATALOADER:
  INPUT_MODE: 's1s2'  # 's1', 's2' or 's1s2'
  INCLUDE_INCOMPLETE: True

AUGMENTATION:
  CROP_SIZE: 64