_BASE_: "base.yaml"
DEBUG: False
MODALITY: 'missing'

MODEL:
  TYPE: 'reconstructionnet_v1'
  TOPOLOGY: [64, 128,]

RECONSTRUCTION_TRAINER:
  LOSS_TYPE: 'L2'
  ALPHA: 0.5

DATALOADER:
  INPUT_MODE: 's1s2'
  INCLUDE_INCOMPLETE: True